version: '3.9'

services:
  db_postgres:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - e.nv
    volumes:
      - db_postgres:/var/lib/postgresql/data

  db_pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '15432:80'
    volumes:
      - db_pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  db_postgres:
  db_pgadmin: